name: React App Deployment 
run-name: ${{ github.actor }} React DeploymentðŸš€
on: 
  push: 
    branches: 
      - main 
jobs: 
  Test-Job: 
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v5
     
    - name: Install Node JS
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    - name: Perform Test Cases
      run : npm run test 

  Build-Job:
     needs: Test-Job
     runs-on: ubuntu-latest 
     steps:
        - name: Checkout
          uses: actions/checkout@v5

        - name: Install Node JS
          uses: actions/setup-node@v4
          with:
            node-version: '20'
            cache: 'npm'

        - name: Perform Build Action 
          run: npm run build 

        
      