name: Git Hub Action Test 
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs: 
  Explore-Git-Hub-Actions: 
    runs-on: ubuntu-latest 
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }}"
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
  Complete-Job: 
    needs: Explore-Git-Hub-Actions
    runs-on: ubuntu-latest 
    steps: 
      - name: step 1 
        run: echo "This is Complete Job!"
        